import { describe, it, expect } from "vitest";
import { MemFS } from "../../src/memfs";
import {
  readLockfile,
  lockfileToResolved,
} from "../../src/npm/lockfile-reader";
import { buildLockfile } from "../../src/npm/index";
import type { ResolvedPackage } from "../../src/npm/resolver";

const sampleLockfile = {
  name: "test-project",
  lockfileVersion: 3,
  packages: {
    "node_modules/react": {
      version: "18.2.0",
      resolved: "https://registry.npmjs.org/react/-/react-18.2.0.tgz",
      dependencies: { "loose-envify": "^1.1.0" },
    },
    "node_modules/react-dom": {
      version: "18.2.0",
      resolved: "https://registry.npmjs.org/react-dom/-/react-dom-18.2.0.tgz",
      dependencies: { react: "^18.2.0", scheduler: "^0.23.0" },
    },
    "node_modules/loose-envify": {
      version: "1.4.0",
      resolved:
        "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz",
    },
  },
};

describe("readLockfile", () => {
  it("returns null when no lockfile exists", () => {
    const vfs = new MemFS();
    expect(readLockfile(vfs, "/")).toBeNull();
  });

  it("returns null for lockfile version < 3", () => {
    const vfs = new MemFS();
    vfs.writeFileSync(
      "/package-lock.json",
      JSON.stringify({
        lockfileVersion: 2,
        packages: {},
      }),
    );
    expect(readLockfile(vfs, "/")).toBeNull();
  });

  it("parses a valid v3 lockfile", () => {
    const vfs = new MemFS();
    vfs.writeFileSync("/package-lock.json", JSON.stringify(sampleLockfile));

    const result = readLockfile(vfs, "/");
    expect(result).not.toBeNull();
    expect(result!.lockfileVersion).toBe(3);
    expect(result!.packages.size).toBe(3);
  });

  it("extracts package entries correctly", () => {
    const vfs = new MemFS();
    vfs.writeFileSync("/package-lock.json", JSON.stringify(sampleLockfile));

    const result = readLockfile(vfs, "/")!;
    const react = result.packages.get("react");
    expect(react).toBeDefined();
    expect(react!.version).toBe("18.2.0");
    expect(react!.resolved).toContain("react-18.2.0.tgz");
    expect(react!.dependencies).toEqual({ "loose-envify": "^1.1.0" });
  });

  it("handles entries without dependencies", () => {
    const vfs = new MemFS();
    vfs.writeFileSync("/package-lock.json", JSON.stringify(sampleLockfile));

    const result = readLockfile(vfs, "/")!;
    const looseEnvify = result.packages.get("loose-envify");
    expect(looseEnvify).toBeDefined();
    expect(looseEnvify!.dependencies).toBeUndefined();
  });

  it("returns null for corrupted JSON", () => {
    const vfs = new MemFS();
    vfs.writeFileSync("/package-lock.json", "not json");
    expect(readLockfile(vfs, "/")).toBeNull();
  });

  it("reads from custom cwd", () => {
    const vfs = new MemFS();
    vfs.mkdirSync("/app", { recursive: true });
    vfs.writeFileSync("/app/package-lock.json", JSON.stringify(sampleLockfile));

    const result = readLockfile(vfs, "/app");
    expect(result).not.toBeNull();
    expect(result!.packages.size).toBe(3);
  });
});

describe("lockfileToResolved", () => {
  it("converts lockfile entries to ResolvedPackage map", () => {
    const vfs = new MemFS();
    vfs.writeFileSync("/package-lock.json", JSON.stringify(sampleLockfile));
    const lockfile = readLockfile(vfs, "/")!;

    const resolved = lockfileToResolved(lockfile);
    expect(resolved.size).toBe(3);

    const react = resolved.get("react")!;
    expect(react.name).toBe("react");
    expect(react.version).toBe("18.2.0");
    expect(react.dist.tarball).toContain("react-18.2.0.tgz");
    expect(react.dependencies).toEqual({ "loose-envify": "^1.1.0" });
  });

  it("entries without dependencies get empty object", () => {
    const vfs = new MemFS();
    vfs.writeFileSync("/package-lock.json", JSON.stringify(sampleLockfile));
    const lockfile = readLockfile(vfs, "/")!;
    const resolved = lockfileToResolved(lockfile);

    const looseEnvify = resolved.get("loose-envify")!;
    expect(looseEnvify.dependencies).toEqual({});
  });
});

describe("round-trip: buildLockfile → readLockfile", () => {
  it("lockfile generated by buildLockfile is consumable by readLockfile", () => {
    const vfs = new MemFS();
    const packages = new Map<string, ResolvedPackage>([
      [
        "lodash",
        {
          name: "lodash",
          version: "4.17.21",
          dist: {
            tarball: "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz",
            shasum: "abc",
          },
          dependencies: {},
        },
      ],
      [
        "express",
        {
          name: "express",
          version: "4.18.2",
          dist: {
            tarball: "https://registry.npmjs.org/express/-/express-4.18.2.tgz",
            shasum: "def",
          },
          dependencies: { accepts: "~1.3.8" },
        },
      ],
    ]);

    // Generate lockfile
    buildLockfile(vfs, packages);

    // Read it back
    const lockfile = readLockfile(vfs, "/");
    expect(lockfile).not.toBeNull();
    expect(lockfile!.packages.size).toBe(2);

    // Convert to resolved and verify
    const resolved = lockfileToResolved(lockfile!);
    expect(resolved.get("lodash")!.version).toBe("4.17.21");
    expect(resolved.get("express")!.dist.tarball).toContain(
      "express-4.18.2.tgz",
    );
    expect(resolved.get("express")!.dependencies).toEqual({
      accepts: "~1.3.8",
    });
  });
});
